nkgilley/python-ecobee-api

pyecobee/__init__.py
setup.py

This is so we can set that value from within home-assistant.
I'm working on a PR for home-assistant to add the fan_min_on_time service, but I need this to be in place first.
Let me know your thoughts on this.

allow setting of the minimum fan on time

---

pyecobee/__init__.py

This proposed routine deletes the indicated vacation event which is required for ecobee to cancel the running vacation hold (or cancel an upcoming vacation hold).

Cancel a vacation hold

---

pyecobee/__init__.py

Change output to use the `logging` module instead of `print()`. When `print()` is used, I see a flood of errors when closing Home Assistant.
Changing to `logging` module will output the errors to the Home Assistant log as they occur.

Fix logging for proper output in logs

---

pyecobee/__init__.py

Ecobee's setHold() function requires that both parameters "coolHoldTemp" and "heatHoldTemp" are integers. 
Since set_hold_temp() doesn't do conversion from float to int it was necessary to pass rounded temperature values into the function:
i.e. if I want to set have cool temperature 75.5 and heat temperature 35.3 I would have to pass 76 and 35 and set_hold_temp() would send 760 and 350 to Ecobee.
This fix allows properly passing floats to set_hold_temp()

fixed set_hold_temp()

---

pyecobee/__init__.py

I just realized, that it would probably be best to catch exceptions on all 'requests' calls rather than just the one I happened to see a failure on...

Wrap all 'requests' called to catch exceptions

---

pyecobee/__init__.py

@nkgilley This PR is ready. I made the `body` a `dict` since the `requests` documentation shows it can be passed that way: 
```python
r = requests.post('http://httpbin.org/post', data = {'key':'value'})
```
This way we don't have to worry about double quotes and string concatenation.  If that's okay with you I can push up another PR that changes the remaining requests the same way.  Or if you'd like I can make this PR the way the other request bodies are currently formatted.

refactor set_fan_mode

---

pyecobee/__init__.py

@nkgilley there was a defect in the refactor where I forgot to convert the temps coming in to an integer.  This was causing some weird behavior in the api.  My apologies.  This PR fixes that.  If you could merge and cut a new package, I'd appreciate it.  Thanks.

convert temps to int

---

.gitignore
pyecobee/__init__.py

Typo preventings Ecobee from using nextTransition and sets a permanent hold.  Tested with my local Ecobee install and resolved the issue.

Fix holdType Typo

---

pyecobee/__init__.py

On each recursive call of `make_request`, json.dumps is called on body. This results in a string that is already json encoded being re-encoded. Everytime this happens back slashes are escaped again creating invalid requests:
(try: `json.dumps(json.dumps(json.dumps('\\')))` for an example of whats going on).
Requests has specific support for json encoded body by using json= instead of data= when making a post request. This avoids the need to encode and I think is the easiest way to solve this issue.

Pass request body with json parameter and do not re-encode json string

---

pyecobee/__init__.py
setup.py

Testing in Home Assistant has revealed that the ecobee API can also throw a 500 status code when the access token needs refreshing. This PR catches 500, and also improves the error log messages to aid in diagnosing problems in the future.

Refresh tokens on 500 status code

---

pyecobee/__init__.py
pyecobee/const.py
pyecobee/errors.py
pyecobee/util.py
setup.py

Refactor the library to use a single request interface to the ecobee API, which has the advantage of unifying error handling and debug logging. Added type and return hinting to class methods. Raise InvalidTokenError when ecobee API response indicates that the refresh token has become invalid (signalling to the client that new tokens need to be obtained from the API, i.e. a new auth process needs to be undertaken). This commit also lays the groundwork for converting the library to async, and as a consequence breaks handling of a passed-in config filename (new method will need to be called after the class constructor is called), but this will not affect Home Assistant as auth is now config-flow-based (no config file is used).

Refactor python-ecobee-api

---

pyecobee/const.py
setup.py

The 5th gen ecobee model is officially called "ecobee Smart Thermostat with Voice Control".

Rename ecobee 5th gen model

---

pyecobee/__init__.py

A problem discovered downstream in Home Assistant:
```
2020-03-04 21:01:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.upstairs fails
Traceback (most recent call last):
File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
await self.async_device_update()
File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
await self.async_update()
File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/components/ecobee/climate.py", line 289, in async_update
await self.data.update()
File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/components/ecobee/__init__.py", line 96, in update
await …
```

Handle json decode errors

---

pyecobee/__init__.py
pyecobee/util.py
setup.py

A followup to #47. If an installation has `simplejson` installed, `requests` will prefer that module over the built-in `json`. Unfortunately, this will also change the exception caught in #47 to `simplejson.errors.JSONDecodeError`. This PR imports `json` in the same manner as `requests` so the namespaces line up properly.
Went ahead and bumped the version, too.

Use simplejson if available, similar to requests

---

pyecobee/__init__.py
setup.py

I'm trying to track down a problem with tokens becoming invalid when this library is used in Home Assistant, and this PR adds debugging to the PIN and token methods to hopefully pinpoint exactly where the problem arises. Version bumped to next patch version (0.2.7).
(Also: try to debug log the request response in json for easier to parse logs, fall back to text response on any exception.)

Improve debug logging

---

pyecobee/__init__.py
setup.py

A change in Home Assistant now requires that we pass the holdHours parameter to set_climate_hold when appropriate. When the holdType is anything other than holdHours, the parameter is omitted.

Fix set climate hold

---

pyecobee/__init__.py

set_fan_hold
- Make optional parameters (holdHours, coolHoldTemp, heatHoldTemp)
- holdHours must be set if holdType is set to holdHours.
- coolHoldTemp and heatHoldTemp are optional. Setting these
values in set_fan_hold can lead to unexpected behavior
This behavior has an issue in the HA repo (home-assistant/core#40087)
set_climate_hold
- Fix comparison which was throwing a python warning.

Updates to set_fan_mode/set_climate_hold

---

pyecobee/__init__.py
setup.py

I'd like to propose a change where refresh_tokens can be called from within the
library's request calls. The following code will watch for an ExpiredTokenError.
If this exception is seen the request call will kick the refresh_tokens and try the
request again. If the second call fails the exception will be passed up the stack.
This is handled by a wrapper function around the _request call. This way the
authentication and token handling can still use the existing logic.
This change handles much of the token expiration behind the scenes, eliminating
many of the issues when expired tokens can sit waiting until the next refresh
to renew those tokens.
This PR also bumps up the requests version in the install_requires list. The existing
version 2.0 is about 8 years old.

Add token_refresh logic to request calls

---

pyecobee/__init__.py

Add the ability to change the outdoor temperature threshold which determines whether the ecobee calls for heat from the main heating source or the aux heating source.  Tested with local changes:
```
>>> e.get_thermostats()
True
>>> e.thermostats[0]['settings']['compressorProtectionMinTemp']
400
>>> e.set_aux_cutover_threshold(0, 45)
>>> e.get_thermostats()
True
>>> e.thermostats[0]['settings']['compressorProtectionMinTemp']
450
```

add a method to set aux heat cutover setting

---

pyecobee/__init__.py
setup.py

This might be an edge use case, but I have added the ability to update the sensors that are involved in the averaging of a climate. This is useful if you use a room occasionally, but when occupied, you want the climate sensor added to the used climate. This would also support removing the added sensor when no longer occupied.
I am sure the follow me functionality might be able to give similar results, but I like the level of control this would provide.
The plan would be for this functionality to be eventually added to Home Assistant as a service.
I will caveat this with I am not a programmer, so while the function works as intended, it may not be best practices. Please feel free to give feedback (looking to get better at Python).
Example function call.
```python
ecobee = …
```

Added function for updating climate sensors

---

pyecobee/__init__.py

This adds the ability to tell an ecobee to toggle the dehumidifier mode, as well as to set the dehumidifier target level. These correspond to `dehumidifierMode` and `dehumidifierLevel`, respectively.
These are intended to be used by a new Home Assistant service I'm working on, as part of this PR: https://github.com/home-assistant/core/pull/93165

Add dehumidifier controls

---

pyecobee/__init__.py
pyecobee/errors.py

Modified the `update_climate_sensors` function to take either sensor names or ids. The need for IDs arises from home assistant needing to use something more unique than the name.

Modified to allow for setting sensors based on IDs
